return {
    ['agricultural-tower'] = {
        --'agricultural-tower',
    },
    ['airborne-pollutant'] = {
        'spores',
    },
    ['ammo-turret'] = {
        --'railgun-turret',
        --'rocket-turret',
    },
    ['ammo'] = {
        'capture-robot-rocket',
        --'railgun-ammo',
        --'tesla-ammo',
    },
    ['armor'] = {
        --'mech-armor',
    },
    ['assembling-machine'] = {
        --'biochamber',
        'captive-biter-spawner',
        'crusher',
        --'cryogenic-plant',
        --'electromagnetic-plant',
        --'foundry',
    },
    ['asteroid'] = {
        'small-metallic-asteroid',
        'small-carbonic-asteroid',
        'small-oxide-asteroid',
        'small-promethium-asteroid',
        'medium-metallic-asteroid',
        'medium-carbonic-asteroid',
        'medium-oxide-asteroid',
        'medium-promethium-asteroid',
        'big-metallic-asteroid',
        'big-carbonic-asteroid',
        'big-oxide-asteroid',
        'big-promethium-asteroid',
        'huge-metallic-asteroid',
        'huge-carbonic-asteroid',
        'huge-oxide-asteroid',
        'huge-promethium-asteroid',
    },
    ['asteroid-chunk'] = {
        'metallic-asteroid-chunk',
        'carbonic-asteroid-chunk',
        'oxide-asteroid-chunk',
        'promethium-asteroid-chunk',
    },
    ['asteroid-collector'] = {
        'asteroid-collector',
    },
    ['autoplace-control'] = {
        'aquilo_crude_oil',
        'fluorine_vent',
        'fulgora_cliff',
        'fulgora_islands',
        'gleba_cliff',
        'gleba_enemy_base',
        'gleba_plants',
        'gleba_stone',
        'gleba_water',
        'lithium_brine',
        'scrap',
        'tungsten_ore',
        'vulcanus_coal',
        'vulcanus_volcanism',
        --'calcite',
        'sulfuric_acid_geyser',
    },
    ['battery-equipment'] = {
        --'battery-mk3-equipment',
    },
    ['burner-usage'] = {
        'nutrients',
        'food',
    },
    ['capsule'] = {
        'yumako-mash',
        'yumako',
        'jellynut',
        'jelly',
        'bioflux',
    },
    ['cargo-bay'] = {
        --'cargo-bay',
    },
    ['change-surface-achievement'] = {
        'visit-aquilo',
        'visit-fulgora',
        'visit-gleba',
        'visit-vulcanus',
    },
    ['cliff'] = {
        'cliff-vulcanus',
        'cliff-gleba',
        'cliff-fulgora',
        'crater-cliff',
    },
    ['complete-objective-achievement'] = {
        'second-star-to-the-right-and-straight-on-till-morning',
    },
    ['corpse'] = {
        --'agricultural-tower-remnants',
        'ashland-lichen-tree-stump',
        'asteroid-collector-remnants',
        'big-demolisher-fissure-scorchmark',
        'big-demolisher-trail-lower',
        'big-demolisher-trail-upper',
        'big-stomper-corpse',
        'big-strafer-corpse',
        'big-wriggler-pentapod-corpse',
        --'biochamber-remnants',
        --'biolab-remnants',
        --'cargo-bay-remnants',
        'crusher-remnants',
        --'cryogenic-plant-remnants',
        --'electromagnetic-plant-remnants',
        --'foundry-remnants',
        --'fusion-generator-remnants',
        --'fusion-reactor-remnants',
        'gleba-spawner-corpse',
        --'heating-tower-remnants',
        'lightning-collector-remnants',
        'lightning-rod-remnants',
        'medium-demolisher-fissure-scorchmark',
        'medium-demolisher-trail-lower',
        'medium-demolisher-trail-upper',
        'medium-stomper-corpse',
        'medium-strafer-corpse',
        'medium-wriggler-pentapod-corpse',
        --'railgun-turret-remnants',
        --'rocket-turret-remnants',
        'small-demolisher-fissure-scorchmark',
        'small-demolisher-trail-lower',
        'small-demolisher-trail-upper',
        'gleba-spawner-corpse-small',
        'small-stomper-corpse',
        'small-strafer-corpse',
        'small-wriggler-pentapod-corpse',
        --'stack-inserter-remnants',
        --'tesla-turret-remnants',
        'thruster-remnants',
        --'turbo-splitter-remnants',
        --'turbo-transport-belt-remnants',
        --'turbo-underground-belt-remnants',
    },
    ['create-platform-achievement'] = {
        'reach-for-the-stars',
    },
    ['delayed-active-trigger'] = {
        'big-demolisher-fissure-explosion-damage-delay',
        'big-demolisher-fissure-explosion-delay',
        'big-demolisher-fissure-explosion-particles-delay',
        'medium-demolisher-fissure-explosion-damage-delay',
        'medium-demolisher-fissure-explosion-delay',
        'medium-demolisher-fissure-explosion-particles-delay',
        'small-demolisher-fissure-explosion-damage-delay',
        'small-demolisher-fissure-explosion-delay',
        'small-demolisher-fissure-explosion-particles-delay',
    },
    ['dont-build-entity-achievement'] = {
        'logistic-network-embargo',
    },
    ['dont-research-before-researching-achievement'] = {
        'rush-to-space',
    },
    ['electric-turret'] = {
        --'tesla-turret',
    },
    ['equip-armor-achievement'] = {
        'look-at-my-shiny-rare-armor',
    },
    ['equipment-grid'] = {
        --'huge-equipment-grid',
    },
    ['explosion'] = {
        --'agricultural-tower-explosion',
        'asteroid-collector-explosion',
        'big-demolisher-fissure',
        --'biochamber-explosion',
        --'biolab-explosion',
        'captive-spawner-explosion-1',
        'captive-spawner-explosion-2',
        --'heating-tower-explosion',
        'medium-demolisher-fissure',
        'small-demolisher-fissure',
        'space-platform-foundation-explosion',
        'thruster-explosion',
    },
    ['fluid'] = {
        --'ammonia',
        --'ammoniacal-solution',
        --'electrolyte',
        --'fluorine',
        --'fluoroketone-cold',
        --'fluoroketone-hot',
        --'fusion-plasma',
        --'holmium-solution',
        --'lava',
        --'lithium-brine',
        --'molten-copper',
        --'molten-iron',
        --'thruster-fuel',
        --'thruster-oxidizer',
    },
    ['fuel-category'] = {
        'food',
        'nutrients',
    },
    ['fusion-generator'] = {
        --'fusion-generator',
    },
    ['fusion-reactor'] = {
        --'fusion-reactor',
    },
    ['generator-equipment'] = {
        --'fusion-reactor-equipment',
    },
    ['group-attack-achievement'] = {
        'get-off-my-lawn',
        'it-stinks-and-they-do-like-it',
    },
    ['gun'] = {
        --'teslagun',
        --'railgun',
    },
    ['inserter'] = {
        --'stack-inserter',
    },
    ['inventory-bonus-equipment'] = {
        --'toolbelt-equipment',
    },
    ['item'] = {
        --'agricultural-tower',
        'artificial-jellynut-soil',
        'artificial-yumako-soil',
        'asteroid-collector',
        --'battery-mk3-equipment',
        --'big-mining-drill',
        --'biochamber',
        'bioflux',
        --'biolab',
        'biter-egg',
        --'calcite',
        'captive-biter-spawner',
        --'carbon-fiber',
        --'carbon',
        'carbonic-asteroid-chunk',
        --'cargo-bay',
        'copper-bacteria',
        'crusher',
        --'cryogenic-plant',
        --'electromagnetic-plant',
        'foundation',
        --'foundry',
        --'fusion-generator',
        --'fusion-power-cell',
        --'fusion-reactor-equipment',
        --'fusion-reactor',
        --'heating-tower',
        --'holmium-ore',
        --'holmium-plate',
        'ice-platform',
        --'ice',
        'iron-bacteria',
        'jellynut-seed',
        'lightning-collector',
        'lightning-rod',
        --'lithium-plate',
        --'lithium',
        'metallic-asteroid-chunk',
        'nutrients',
        'overgrowth-jellynut-soil',
        'overgrowth-yumako-soil',
        'oxide-asteroid-chunk',
        'pentapod-egg',
        'promethium-asteroid-chunk',
        --'quantum-processor',
        --'railgun-turret',
        --'rocket-turret',
        'scrap',
        'space-platform-foundation',
        'space-platform-hub',
        'space-platform-starter-pack',
        'spoilage',
        --'stack-inserter',
        --'supercapacitor',
        --'superconductor',
        --'tesla-turret',
        'thruster',
        --'toolbelt-equipment',
        --'tree-seed',
        --'tungsten-carbide',
        --'tungsten-ore',
        --'tungsten-plate',
        --'turbo-loader',
        --'turbo-splitter',
        --'turbo-transport-belt',
        --'turbo-underground-belt',
        'yumako-seed',
    },
    ['item-group'] = {
        'space',
    },
    ['item-subgroup'] = {
        --'agriculture-explosions',
        'agriculture-processes',
        'agriculture-products',
        --'agriculture-remnants',
        'agriculture',
        'aquilo-processes',
        --'environmental-protection-explosions',
        --'environmental-protection-remnants',
        'environmental-protection',
        'fulgora-processes',
        'nauvis-agriculture',
        'planet-connections',
        'planets',
        'space-crushing',
        'space-environment',
        'space-interactors',
        'space-material',
        'space-platform-explosions',
        'space-platform-remnants',
        'space-platform',
        'space-processing',
        'space-rocket',
        --'vulcanus-processes',
    },
    ['kill-achievement'] = {
        'if-it-bleeds',
        'size-doesnt-matter',
        'we-need-bigger-guns',
    },
    ['lab'] = {
        --'biolab',
    },
    ['lightning'] = {
        'lightning',
    },
    ['lightning-attractor'] = {
        'fulgoran-ruin-attractor',
        'lightning-collector',
        'lightning-rod',
    },
    ['loader'] = {
        --'turbo-loader',
    },
    ['mining-drill'] = {
        --'big-mining-drill',
    },
    ['place-equipment-achievement'] = {
        'no-room-for-more',
    },
    ['planet'] = {
        'aquilo',
        'fulgora',
        'gleba',
        'vulcanus',
    },
    ['plant'] = {
        'jellystem',
        'yumako-tree',
    },
    ['procession-layer-inheritance-group'] = {
        'procession-stars-bg',
    },
    ['procession'] = {
        'planet-to-platform-a',
        'planet-to-platform-b',
        'platform-to-planet-a',
        'platform-to-planet-b',
        'planet-to-platform-intermezzo',
        'platform-to-planet-intermezzo',
    },
    ['projectile'] = {
        'small-strafer-projectile',
        'medium-strafer-projectile',
        'big-strafer-projectile',
    },
    ['reactor'] = {
        --'heating-tower',
    },
    ['recipe'] = {
        --'acid-neutralisation',
        'advanced-carbonic-asteroid-crushing',
        'advanced-metallic-asteroid-crushing',
        'advanced-oxide-asteroid-crushing',
        'advanced-thruster-fuel',
        'advanced-thruster-oxidizer',
        'agricultural-science-pack',
        --'agricultural-tower',
        --'ammonia-rocket-fuel',
        --'ammoniacal-solution-separation',
        'artificial-jellynut-soil',
        'artificial-yumako-soil',
        'asteroid-collector',
        --'battery-mk3-equipment',
        --'big-mining-drill',
        --'biochamber',
        'bioflux',
        --'biolab',
        'biolubricant',
        'bioplastic',
        'biosulfur',
        'biter-egg',
        'burnt-spoilage',
        'captive-biter-spawner',
        'capture-robot-rocket',
        --'carbon-fiber',
        --'carbon',
        'carbonic-asteroid-crushing',
        'carbonic-asteroid-reprocessing',
        --'cargo-bay',
        --'casting-copper-cable',
        --'casting-copper',
        --'casting-iron-gear-wheel',
        --'casting-iron-stick',
        --'casting-iron',
        --'casting-low-density-structure',
        --'casting-pipe-to-ground',
        --'casting-pipe',
        --'casting-steel',
        --'coal-synthesis',
        --'concrete-from-molten-iron',
        'copper-bacteria-cultivation',
        'copper-bacteria',
        'crusher',
        --'cryogenic-plant',
        'cryogenic-science-pack',
        'electrolyte',
        --'electromagnetic-plant',
        'electromagnetic-science-pack',
        'fish-breeding',
        --'fluoroketone-cooling',
        --'fluoroketone',
        'foundation',
        --'foundry',
        --'fusion-generator',
        --'fusion-power-cell',
        --'fusion-reactor-equipment',
        --'fusion-reactor',
        --'heating-tower',
        --'holmium-plate',
        --'holmium-solution',
        --'ice-melting',
        'ice-platform',
        'iron-bacteria-cultivation',
        'iron-bacteria',
        'jellynut-processing',
        'lightning-collector',
        'lightning-rod',
        'lightning-rod',
        'ligthning-collector',
        --'lithium-plate',
        --'lithium',
        --'mech-armor',
        'metallic-asteroid-crushing',
        'metallic-asteroid-reprocessing',
        'metallurgic-science-pack',
        --'molten-copper-from-lava',
        --'molten-copper',
        --'molten-iron-from-lava',
        --'molten-iron',
        'nutrients-from-bioflux',
        'nutrients-from-biter-egg',
        'nutrients-from-fish',
        'nutrients-from-spoilage',
        'nutrients-from-yumako-mash',
        'overgrowth-jellynut-soil',
        'overgrowth-yumako-soil',
        'oxide-asteroid-crushing',
        'oxide-asteroid-reprocessing',
        'pentapod-egg',
        'promethium-science-pack',
        --'quantum-processor',
        --'railgun-ammo',
        --'railgun-turret',
        --'railgun',
        --'recycler',
        'rocket-fuel-from-jelly',
        --'rocket-turret',
        'scrap-recycling',
        --'simple-coal-liquefaction',
        --'solid-fuel-from-ammonia',
        'space-platform-foundation',
        'space-platform-starter-pack',
        'space-science-pack',
        --'stack-inserter',
        --'steam-condensation',
        --'supercapacitor',
        --'superconductor',
        --'tesla-ammo',
        --'tesla-turret',
        --'teslagun',
        'thruster-fuel',
        'thruster-oxidizer',
        'thruster',
        --'toolbelt-equipment',
        --'tungsten-carbide',
        --'tungsten-plate',
        --'turbo-loader',
        --'turbo-splitter',
        --'turbo-transport-belt',
        --'turbo-underground-belt',
        --'wood-processing',
        'yumako-processing',
    },
    ['recipe-category'] = {
        --'cryogenics-or-assembling',
        --'cryogenics',
        --'electronics-or-assembling',
        --'electronics-with-fluid',
        --'electronics',
        --'crafting-with-fluid-or-metallurgy',
        --'metallurgy-or-assembling',
        --'metallurgy',
        'captive-spawner-process',
        'chemistry-or-cryogenics',
        'crushing',
        'electromagnetics',
        'organic-or-assembling',
        'organic-or-chemistry',
        'organic-or-hand-crafting',
        --'organic',
        'pressing',
    },
    ['research-with-science-pack-achievement'] = {
        'research-with-agriculture',
        'research-with-cryogenics',
        'research-with-electromagnetics',
        'research-with-metallurgics',
        'research-with-promethium',
    },
    ['resource'] = {
        --'calcite',
        --'fluorine-vent',
        --'lithium-brine',
        'scrap',
        'sulfuric-acid-geyser',
        --'tungsten-ore',
    },
    ['segmented-unit'] = {
        'big-demolisher',
        'medium-demolisher',
        'small-demolisher',
    },
    ['simple-entity'] = {
        'big-fulgora-rock',
        'vulcanus-chimney-short',
        'vulcanus-chimney-truncated',
        'vulcanus-chimney',
        'vulcanus-chimney-cold',
        'vulcanus-chimney-faded',
        'small-stomper-shell',
        'medium-stomper-shell',
        'big-stomper-shell',
        'small-demolisher-corpse',
        'medium-demolisher-corpse',
        'big-demolisher-corpse',
        'huge-volcanic-rock',
        'big-volcanic-rock',
        'fulgoran-ruin-small',
        'fulgoran-ruin-medium',
        'fulgoran-ruin-big',
        'fulgoran-ruin-huge',
        'fulgoran-ruin-colossal',
        'fulgoran-ruin-vault',
        'fulgoran-ruin-stonehenge',
        'fulgurite-small',
        'fulgurite',
        'iron-stromatolite',
        'copper-stromatolite',
        'lithium-iceberg-huge',
        'lithium-iceberg-big',
    },
    ['space-connection-distance-traveled-achievement'] = {
        'shattered-planet-1',
        'shattered-planet-2',
        'shattered-planet-3',
    },
    ['space-connection'] = {
        'nauvis-vulcanus',
        'nauvis-gleba',
        'nauvis-fulgora',
        'vulcanus-gleba',
        'gleba-fulgora',
        'gleba-aquilo',
        'fulgora-aquilo',
        'aquilo-solar-system-edge',
        'solar-system-edge-shattered-planet',
    },
    ['space-location'] = {
        'solar-system-edge',
        'shattered-planet',
    },
    ['space-platform-hub'] = {
        'space-platform-hub',
    },
    ['space-platform-starter-pack'] = {
        'space-platform-starter-pack',
    },
    ['spider-unit'] = {
        'big-stomper-pentapod',
        'big-strafer-pentapod',
        'medium-stomper-pentapod',
        'medium-strafer-pentapod',
        'small-stomper-pentapod',
        'small-strafer-pentapod',
    },
    ['splitter'] = {
        --'turbo-splitter',
    },
    ['surface'] = {
        'space-platform',
    },
    ['technology'] = {
        'advanced-asteroid-processing',
        'agricultural-science-pack',
        --'agriculture',
        'artificial-soil',
        --'artillery-shell-damage-1',
        'asteroid-productivity',
        'asteroid-reprocessing',
        'bacteria-cultivation',
        --'battery-mk3-equipment',
        --'big-mining-drill',
        --'biochamber',
        'bioflux-processing',
        'bioflux',
        --'biolab',
        'biter-egg-handling',
        --'calcite-processing',
        'captive-biter-spawner',
        'captivity',
        --'carbon-fiber',
        --'cryogenic-plant',
        'cryogenic-science-pack',
        --'electric-weapons-damage-1',
        --'electric-weapons-damage-2',
        --'electric-weapons-damage-3',
        --'electric-weapons-damage-4',
        --'electromagnetic-plant',
        'electromagnetic-science-pack',
        'fish-breeding',
        'foundation',
        --'foundry',
        --'fusion-reactor-equipment',
        --'fusion-reactor',
        --'health',
        --'heating-tower',
        --'holmium-processing',
        'jellynut',
        'lightning-collector',
        --'lithium-processing',
        --'low-density-structure-productivity',
        --'mech-armor',
        'metallurgic-science-pack',
        'overgrowth-soil',
        'planet-discovery-aquilo',
        'planet-discovery-fulgora',
        'planet-discovery-gleba',
        'planet-discovery-vulcanus',
        --'plastic-bar-productivity',
        --'processing-unit-productivity',
        'promethium-science-pack',
        --'quantum-processor',
        'rail-support-foundations',
        --'railgun-damage-1',
        --'railgun-shooting-speed-1',
        --'railgun',
        --'recycling',
        --'research-productivity',
        --'rocket-fuel-productivity',
        --'rocket-part-productivity',
        --'rocket-turret',
        'scrap-recycling-productivity',
        'space-platform-thruster',
        'space-platform',
        --'stack-inserter',
        --'steel-plate-productivity',
        --'tesla-weapons',
        --'toolbelt-equipment',
        --'transport-belt-capacity-1',
        --'transport-belt-capacity-2',
        --'tree-seeding',
        --'tungsten-carbide',
        --'tungsten-steel',
        --'turbo-transport-belt',
        'yumako',
        --'worker-robots-speed-7',
    },
    ['thruster'] = {
        'thruster',
    },
    ['tips-and-tricks-item-category'] = {
        'space-age',
        'space-platform',
        'spoilables',
    },
    ['tips-and-tricks-item'] = {
        'fulgora-briefing',
        'lightning-mechanics',
        'gleba-briefing',
        'agriculture',
        'vulcanus-briefing',
        'lava-processing',
        'aquilo-briefing',
        'heating-mechanics',
        'space-platform',
        'orbital-logistics',
        'removing-trash-in-space',
        'space-science',
        'asteroid-defense',
        'spoilables',
        'spoilables-result',
        'spoilables-research',
    },
    ['tool'] = {
        'agricultural-science-pack',
        'cryogenic-science-pack',
        'electromagnetic-science-pack',
        'metallurgic-science-pack',
        'promethium-science-pack',
    },
    ['transport-belt'] = {
        --'turbo-transport-belt',
    },
    ['tree'] = {
        'ashland-lichen-tree',
        'ashland-lichen-tree-flaming',
        'boompuff',
        'copper-stromatolite',
        'cuttlepop',
        'fulgurite-small',
        'fulgurite',
        'funneltrunk',
        'hairyclubnub',
        'iron-stromatolite',
        'jellystem',
        'lickmaw',
        'slipstack',
        'stingfrond',
        'sunnycomb',
        'teflilly',
        'yumako-tree',
        'water-cane',
    },
    ['underground-belt'] = {
        --'turbo-underground-belt',
    },
    ['unit-spawner'] = {
        'gleba-spawner-small',
        'gleba-spawner',
    },
    ['unit'] = {
        'big-stomper-pentapod',
        'big-strafer-pentapod',
        'big-wriggler-pentapod-premature',
        'big-wriggler-pentapod',
        'medium-stomper-pentapod',
        'medium-strafer-pentapod',
        'medium-wriggler-pentapod-premature',
        'medium-wriggler-pentapod',
        'small-stomper-pentapod',
        'small-strafer-pentapod',
        'small-wriggler-pentapod-premature',
        'small-wriggler-pentapod',
    },
    ['use-entity-in-energy-production-achievement'] = {
        'fusion-power',
    },
    ['use-item-achievement'] = {
        'todays-fish-is-trout-a-la-creme',
    },
}
